config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    resources :homes, only: [:top, :about]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:new, :index, :update, :destroy, :create, :edit]
    resources :genres, only: [:show]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/confirm' => "orders#confirm"
    post 'orders/confirm' => "orders#confirm"
    get 'orders/thanks' => "orders#thanks"
    resources :orders, only: [:new, :index, :show, :create]

    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    get 'customers/mypage' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers/edit' => "customers#update"
    get 'customers/mypage/withdrawal' => "customers#unsubscribe"
    patch 'customers/mypage/withdrawal' => 'customers#withdrawal'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image

  # belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  # def get_item_image(width, height)
  # item_image.variant(resize_to_limit: [width, height]).processed
  # end

  def get_item_image(width, height)
    item_image.variant(resize_to_limit: [width, height]).processed
  end

  def taxin_price
    price * 1.1
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :genre_id, :name, :introduction, :price, :is_active)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<main>
<div class="container px-5 px-sm-0">

    <h4>商品編集</h4>
    <%= form_with model: @item, url: admin_item_path do |f| %>
      <label for="inputname">商品画像</label><br>
      <%= f.file_field :item_image, accept: "image/*" %><br>
      <label for="inputname">商品名</label><br>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"商品名" %><br>
      <label for="inputIntroduction">商品説明</label><br>
      <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction", placeholder:"商品説明" %><br>
      <label for="inputPrice">税抜価格</label><br>
      <%= f.text_area :price, autofocus: true, id:"inputPrice", placeholder:"税抜価格" %><br>
      <label for="inputGenre_id">ジャンル</label><br>
      <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name), autofocus: true, id:"inputGenre_id", placeholder: @item.genre.name %><br>
      
      <label for="inputIs_active">販売ステータス</label><br>
      <%= f.radio_button :is_active, :true %>
      <p>販売中</p>
      <%= f.radio_button :is_active, :false %> <br>
      <p>販売停止中</p>
      
      <%= f.submit '変更を保存' %>
    <% end %>

  </div>
</main>  

app/views/admin/items/index.html.erb
<main>
<div class="container px-5 px-sm-0">
  <h4>商品一覧</h4>
  <%= link_to '新規登録', new_admin_item_path %>
 　   <div class="row">
          <% @items.each do |item| %>
        <div class="col-xl-2">
            <p>商品ID：<%= item.id %></p>
        </div>   
        <div class="col-xl-2">
            <p>商品名：<%= link_to item.name, admin_item_path(item.id) %></p>
        </div>   
        <div class="col-xl-2">    
            <p>税込価格：<%= (item.price.to_i * 1.1).floor %></p>
        </div>   
        <div class="col-xl-2">    
            <p>ジャンル: <%= item.genre.name %></p>
        </div>   
        <div class="col-xl-2">    
            <p>ステータス：
            <% if item.is_active == true %>
             販売中
            <% else %>
             販売停止中
            <% end %>
            </p>
         </div> 
        <p>-----------------------------------------------------------------------------------------------------------------------------------------------------------</p>
          <% end %>
      </div> 
      <%= paginate @items %>
</div>     
</main>

app/views/admin/items/new.html.erb
<main>
<div class="container px-5 px-sm-0">


      <h4>商品新規登録</h4>
       <%= form_with model: @item, url: admin_items_path, local: true do |f| %>

          商品画像
              <%= f.file_field :item_image, accept: "image/*" %><br>
          商品名
            <%= f.text_field :name, placeholder:"商品名" %><br>
          商品説明
            <%= f.text_area :introduction, placeholder:"ここに説明文を記載します" %><br>
          ジャンル
          <%= f.select :genre_id, options_from_collection_for_select(@genres, :id, :name) %><br>
          税抜価格
          <%= f.text_field :price, placeholder:"1000"  %>円<br>
          販売ステータス<br>
          <%= f.radio_button :is_active, :true %><br>
          <p>販売中</p>
          <%= f.radio_button :is_active, :false %> <br>
          <p>販売停止中</p>
          <%= f.submit '新規投稿' %>
        <% end %>

  </div>
</main>

app/views/admin/items/show.html.erb
<main>
<div class="container px-5 px-sm-0">

    <h4>商品詳細</h4>
     <div class="row">
      <div class="col-xl-4">
      <%= image_tag @item.get_item_image(300,300) %>
      </div>   
      <div class="col-xl-3">
      <p>商品名：<%= @item.name %></p>
      <p>商品説明：<%= @item.introduction %></p>
      <p>税込価格：<%= (@item.price.to_i * 1.1).floor %>(<%= @item.price %>)円</p>
      <p>ジャンル: <%= @item.genre.name %></p>
      <p>販売ステータス：
      <% if @item.is_active == true %>
       販売中
      <% else %>
       販売停止中
      <% end %>
      </p>
      <%= link_to "編集する", edit_admin_item_path %>
      </div> 
    </div>
    
  
  </div>
</main>  