config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    resources :homes, only: [:top, :about]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:new, :index, :update, :destroy, :create, :edit]
    resources :genres, only: [:show]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/confirm' => "orders#confirm"
    post 'orders/confirm' => "orders#confirm"
    get 'orders/thanks' => "orders#thanks"
    resources :orders, only: [:new, :index, :show, :create]

    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    get 'customers/mypage' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers/edit' => "customers#update"
    get 'customers/mypage/withdrawal' => "customers#unsubscribe"
    patch 'customers/mypage/withdrawal' => 'customers#withdrawal'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customers_path
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_deleted)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<main>
　<div class="container px-5 px-sm-0">   

      <h3><%= @customer.last_name + @customer.first_name %>さん会員詳細</h3>
      <%= form_with model: @customer, url: admin_customer_path, local: true do |f| %>
      　会員ID:<%= @customer.id %><br>
      　<label for="inputLast_name">氏名</label>
        <%= f.text_field :last_name, autofocus: true, id:"inputLast_name", placeholder:"性" %>
        <label for="inputFirst_name"></label>
        <%= f.text_field :first_name, autofocus: true, id:"inputFirst_name", placeholder:"名" %><br>
        
        <label for="inputLast_name_kana">フリガナ</label>
        <%= f.text_field :last_name_kana, autofocus: true, id:"inputLast_name_kana", placeholder:"セイ" %>
        <label for="inputFirst_name_kana"></label>
        <%= f.text_field :first_name_kana, autofocus: true, id:"inputFirst_name_kana", placeholder:"メイ" %><br>
        
        <label for="inputPostal_code">郵便番号</label>
        <%= f.text_field :postal_code, autofocus: true, id:"inputPostal_code", placeholder:"郵便番号" %><br>
        
        <label for="inputAddress">住所</label>
        <%= f.text_field :address, autofocus: true, id:"inputAddress", placeholder:"住所" %><br>
        
        <label for="inputTelephone_number">電話番号</label>
        <%= f.text_field :telephone_number, autofocus: true, id:"inputTelephone_number", placeholder:"電話番号" %><br>
        
        <label for="inputEmail">メールアドレス</label>
        <%= f.text_field :email, autofocus: true, id:"inputEmail", placeholder:"メールアドレス" %><br>
        
        <label for="inputIs_deleted">会員ステータス</label><br>
        <%= f.radio_button :is_deleted, :false %>
        <p>有効</p>
        <%= f.radio_button :is_deleted, :true %> <br>
        <p>退会</p>
      
        <%= f.submit "変更を保存する" %>
      <% end %>

  </div>
</main> 

app/views/admin/customers/index.html.erb
<main>
　<div class="container px-5 px-sm-0">

    <h5>会員一覧</h5>
    <% @customers.each do |customer| %>
     <div class="row">
      ID:<%= customer.id %>
      氏名:<%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %>
      メールアドレス:<%= customer.email %>
      <p>ステータス：
            <% if customer.is_deleted == false %>
             有効
            <% else %>
             退会
            <% end %>
            </p>
     </div>
    <% end %>
    <%= paginate @customers %>
  </div>
</main>

app/views/admin/customers/show.html.erb
<main>
　<div class="container px-5 px-sm-0">      
      
      <h5><%= @customer.last_name + @customer.first_name %>さん会員詳細</h5>
      
        会員ID:<%= @customer.id %><br>
        氏名:<%= @customer.last_name + @customer.first_name%><br>
        フリガナ:<%= @customer.last_name_kana + @customer.first_name_kana %><br>
        郵便番号:<%= @customer.postal_code %><br>
        住所:<%= @customer.address %><br>
        電話番号:<%= @customer.telephone_number%><br>
        メールアドレス:<%= @customer.email %><br>
        会員ステータス:<% if @customer.is_deleted == false %>
                        有効
                       <% else %>
                        退会
                      <% end %>
            
      
        <p><%= link_to "編集する", edit_admin_customer_path %></p>
        <p><%= link_to "注文履歴一覧を見る", admin_items_path %></p>
  </div>
</main>        