config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    resources :homes, only: [:top, :about]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:new, :index, :update, :destroy, :create, :edit]
    resources :genres, only: [:show]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/confirm' => "orders#confirm"
    post 'orders/confirm' => "orders#confirm"
    get 'orders/thanks' => "orders#thanks"
    resources :orders, only: [:new, :index, :show, :create]

    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    get 'customers/mypage' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers/edit' => "customers#update"
    get 'customers/mypage/withdrawal' => "customers#unsubscribe"
    patch 'customers/mypage/withdrawal' => 'customers#withdrawal'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<main>
　<div class="container px-5 px-sm-0">

    <h3>ジャンル編集する</h3>
    <%= form_with model: @genre, url: admin_genre_path do |f| %>
    <label for="inputName">ジャンル名</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ジャンル名" %>
      <%= f.submit "変更を保存" %>
    <% end %>
    
  </div>
</main>     

app/views/admin/genres/index.html.erb
<main>
　<div class="container px-5 px-sm-0">


    <h5>ジャンル一覧・追加</h5>
    <%= form_with model: @genre, url: admin_genres_path do |f| %>
    <label for="inputName">ジャンル名</label>
      <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"ジャンル名" %>
      <%= f.submit "新規登録" %>
    <% end %>
    <p>----------------------------------------------------------------------</p>
    ジャンル一覧
    
        <% @genres.each do |genre| %>
    <div class="row">    
      <div class="col-xl-2">  
        <%= genre.name %>
      </div>
      <div class="col-xl-2">
        <p><%= link_to "編集する", edit_admin_genre_path(genre) %></p>
      </div> 
    </div>
     <p>---------------------------------------------------------</p>
        <% end %>
       
  </div>
</main>  