config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions',
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions",
  }

  namespace :admin do
    root to: 'homes#top'
    resources :items, only: [:new, :index, :show, :edit, :create, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :genres, only: [:index, :create, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end

  scope module: :public do
    resources :homes, only: [:top, :about]
    resources :items, only: [:index, :show]
    resources :addresses, only: [:new, :index, :update, :destroy, :create, :edit]
    resources :genres, only: [:show]

    delete "cart_items/destroy_all" => 'cart_items#destroy_all'
    resources :cart_items, only: [:index, :update, :destroy, :create]

    get 'orders/confirm' => "orders#confirm"
    post 'orders/confirm' => "orders#confirm"
    get 'orders/thanks' => "orders#thanks"
    resources :orders, only: [:new, :index, :show, :create]

    root to: 'homes#top'
    get 'about' => "homes#about", as: "about"

    get 'customers/mypage' => "customers#show"
    get 'customers/edit' => "customers#edit"
    patch 'customers/edit' => "customers#update"
    get 'customers/mypage/withdrawal' => "customers#unsubscribe"
    patch 'customers/mypage/withdrawal' => 'customers#withdrawal'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def view_address_and_name
    "〒" + postal_code + "   " + address + "   " + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def sum_of_price
    item.taxin_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :addresses, dependent: :destroy

  validates :email, presence: true
  validates :last_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :last_name_kana, presence: true
  validates :first_name_kana, presence: true
  validates :postal_code, presence: true
  validates :address, presence: true
  validates :telephone_number, presence: true
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :item_image

  # belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_details
  belongs_to :genre

  # def get_item_image(width, height)
  # item_image.variant(resize_to_limit: [width, height]).processed
  # end

  def get_item_image(width, height)
    item_image.variant(resize_to_limit: [width, height]).processed
  end

  def taxin_price
    price * 1.1
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { payment_waiting: 0, payment_confirm: 1, in_production: 2, preparing_delivery: 3, delivered: 4 }
  # enum status: [payment_waiting, payment_confirmation, in_production, delivery_preparation, delivered]
  # enum status: { payment_waiting: 0, payment_confirmation: 1, in_production: 2, delivery_preparation: 3, delivered: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order

  enum making_status: { production_not_possible: 0, production_pending: 1, in_production: 2, production_complete: 3 }
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!
  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
  end

  private

  def order_params
    params.require(:order).permit(:customer_id, :payment_method, :postal_code, :address, :name, :shipping_cost, :billing_amount, :status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:order_id, :item_id, :price, :amount, :making_status)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def index
    @items = Item.page(params[:page]).per(10)
    @genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_item_path(@item.id)
  end

  def edit
    @item = Item.find(params[:id])
    @genres = Genre.all
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:item_image, :genre_id, :name, :introduction, :price, :is_active)
  end

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_admin!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_root_path
    when Customer
      root_path
    end
  end

  def after_sign_out_path_for(resource)
    case resource
    when :admin
      new_admin_session_path
    when :customer
      root_path
    end
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :name, :last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :is_active])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #E4AEC5 !important;">
        <div class="container">
          <a class="navbar-brand" href="/">
              <span>Nagano Cake</span>
          </a>

         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
                 <li class="nav-item">
                   <%= link_to admin_items_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  商品一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to admin_customers_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  会員一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to admin_root_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  注文履歴一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  ジャンル一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>  ログアウト
                   <% end %>
                 </li>

            <% elsif customer_signed_in? %>
                 <li class="nav-item">
                   <%= link_to customers_mypage_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  マイページ
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to items_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  商品一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to cart_items_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-home"></i>  カート
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to destroy_customer_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>  ログアウト
                   <% end %>
                 </li>
            <% else %>

                 <li class="nav-item">
                   <%= link_to about_path class: 'nav-link text-light' do %>
                   about
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to items_path class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>  商品一覧
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to new_customer_registration_path class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>  新規登録
                   <% end %>
                 </li>

                 <li class="nav-item">
                   <%= link_to new_customer_session_path class: 'nav-link text-light' do %>
                 <i class="fas fa-home"></i>  ログイン
                   <% end %>
                 </li>
            <% end %>
           </ul>
         </div>
       </div>
     </nav>
   </header>

    <%= yield %>
  </body>
</html>